[package]
authors = [ "Yiran Lu <me@yiranls.cc>" ]
autoexamples = false
categories = [ "parser-implementations", "parsing", "text-editors" ]
description = "Commonlisp grammar for tree-sitter"
edition = "2024"
keywords = [ "incremental", "parsing", "tree-sitter", "commonlisp" ]
license = "MIT"
name = "tree-sitter-commonlisp"
readme = "README.md"
repository = "https://github.com/tree-sitter/tree-sitter-commonlisp"
version = "0.1.0"

build = "bindings/rust/build.rs"
include = [ "bindings/rust/*", "grammar.js", "queries/*", "src/*", "tree-sitter.json", "/LICENSE" ]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.27.0"
