((token) @keyword
         (#any-of? @keyword
          "call-with-input-file"
          "call-with-input-string"
          "call-with-output-file"
          "call-with-output-string"
          "call-with-prompt"
          "call-with-trace"
          "define-accessor"
          "define-class"
          "define-enumeration"
          "define-inlinable"
          "define-syntax-parameter"
          "eval-when"
          "lambda*"
          "syntax-parameterize"
          "use-modules"
          "with-error-to-file"
          "with-error-to-port"
          "with-error-to-string"
          "with-fluid*"
          "with-fluids"
          "with-fluids*"
          "with-input-from-port"
          "with-input-from-string"
          "with-output-to-port"
          "with-output-to-string"))
